dbt_red_metropolitana:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      user: "{{ env_var('DB_USER', 'amt_admin') }}"
      password: "{{ env_var('DB_PASSWORD', 'amt_secure_pass') }}"
      port: "{{ env_var('DB_PORT', '5432') | int }}"
      dbname: "{{ env_var('DB_NAME', 'amt_dw') }}"
      schema: public
      threads: 4
      keepalives_idle: 0